### ISSUE TITLE
API routes

### ISSUE THREAD

**Issue by Zio-4** [chingu-voyages/v41-bears-team-24#30]

**Comment by RParkerM** [comment]
I suggest: create an order (POST), get all orders (LIST), get a single order (GET), change order status (PUT)

**Comment by Zio-4** [comment]
- Cart: /API/cart
- Menu category: /API/menucategory
   - Food item: /API/menucategory/fooditem 
- Orders: /API/orders
-Sign in: /API/signin
- Signup: /API/signup

**Comment by Zio-4** [comment]
- Cart: /API/cart
- Menu category: /API/menucategory
   - Food item: /API/menucategory/fooditem 
- Orders: /API/orders
-Sign in: /API/signin
- Signup: /API/signup
